import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "5 beehiiv Features Most People Miss", description: "beehiiv Scale ($49/mo) includes Boost ad network, referral program, and 3D analytics. Launch (free) includes custom domains. Growth features most creators overlook." };
export default function Page() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">5 beehiiv Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">5 beehiiv Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">beehiiv is known for newsletters, but the Boost ad network, referral program, paid subscriptions, polls, and 3D analytics dashboard are what make it a business platform, not just an email tool.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Boost Network — Earn Revenue (Scale — $49/mo)</h2><p className="text-muted leading-relaxed mb-2">Get paid to recommend other newsletters. Earn $1-$5 per subscriber acquired through Boost recommendations. Can offset or exceed the $49/mo subscription cost.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Newsletter revenue without selling your own products. Some creators earn $500+/month from Boosts alone.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Referral Program (Scale — $49/mo)</h2><p className="text-muted leading-relaxed mb-2">Built-in referral system where subscribers earn rewards for referring friends. Configurable milestones and rewards. Replaces SparkLoop ($20/mo+) for organic growth.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Organic subscriber growth without a separate referral tool.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Polls and Surveys (Scale — $49/mo)</h2><p className="text-muted leading-relaxed mb-2">Embed polls in newsletters to increase engagement and collect audience insights. Results visible in analytics. Most email tools require a separate survey tool like Typeform.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> First-party audience data without leaving the newsletter platform.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Custom Domains (Launch — $0)</h2><p className="text-muted leading-relaxed mb-2">Custom domain support on the free tier. Your newsletter lives at newsletter.yourdomain.com, not yourname.beehiiv.com. Most platforms reserve custom domains for paid tiers.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Brand ownership from day one, even on the free plan.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. 3D Analytics Dashboard (Scale — $49/mo)</h2><p className="text-muted leading-relaxed mb-2">Advanced analytics with subscriber acquisition sources, engagement heatmaps, and growth trends. More detailed than most email platforms analytics on comparable tiers.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Deep audience insights without Google Analytics or Mixpanel.</p></div></section>
      <RelatedLinks tools={["beehiiv"]} comparisons={[]} guides={["beehiiv-pricing-explained", "is-beehiiv-better-than-substack", "beehiiv-setup-guide"]} />
    </div></article></>);
}
