import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "5 Pipedrive Features Most People Miss", description: "Pipedrive Lite ($14/seat) includes web forms and chatbot. Growth ($39/seat) adds automations, scheduler, and group email. Hidden features that boost sales productivity." };
export default function PipedriveFeaturesMostPeopleMissPage() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">Pipedrive Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">5 Pipedrive Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">Pipedrive is known for its pipeline view, but it includes web forms, a chatbot, activity tracking insights, and an AI sales assistant that most users overlook.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>9 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Web Forms (Lite — $14/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Embeddable web forms that create leads directly in your pipeline. No Typeform or Tally needed for basic lead capture. Available on the lowest paid tier.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Form-to-pipeline without a separate form tool or Zapier integration.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Chatbot / LeadBooster (Add-on — $32.50/mo)</h2><p className="text-muted leading-relaxed mb-2">A chatbot that qualifies website visitors and routes them to your pipeline. Includes live chat, chatbot, prospector, and web forms in one add-on. Most users buy Intercom ($39/seat) without considering Pipedrive LeadBooster.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Lead qualification chatbot integrated directly with your CRM pipeline.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. AI Sales Assistant (All tiers)</h2><p className="text-muted leading-relaxed mb-2">Pipedrive AI assistant analyzes your sales activity and suggests next actions: follow up on stale deals, prioritize high-value opportunities, and flag deals at risk. Available on all paid tiers.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> AI-powered sales coaching without a separate tool like Gong or Chorus.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Automations (Growth — $39/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Build if-then automations: when a deal moves to Won, create a task. When a contact is added, send an email. Growth tier includes automations that replace simple Zapier workflows.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> CRM-native automation without Zapier ($29.99/mo) for common sales workflows.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Revenue Forecasting (Premium — $49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Recurring revenue tracking, forecasting dashboards, and deal probability calculations. Premium tier unlocks revenue forecasts that most teams build in spreadsheets.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Sales forecasting without a BI tool. But $49/seat is a big jump from Lite ($14/seat).</p></div></section>
      <RelatedLinks tools={["pipedrive"]} comparisons={["hubspot-crm-vs-pipedrive"]} guides={["pipedrive-pricing-explained", "is-pipedrive-good-for-startups", "pipedrive-setup-guide"]} />
    </div></article></>);
}
