import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "5 Mailchimp Features Most People Miss", description: "Mailchimp Free includes landing pages and postcards. Standard ($20/mo) adds customer journey builder and content optimizer. Hidden features beyond basic email campaigns." };
export default function Page() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">5 Mailchimp Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">5 Mailchimp Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">Most users send campaigns and ignore everything else. Mailchimp includes landing pages, postcards, social posting, and a content optimizer that most users never touch.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Landing Pages (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Build landing pages directly in Mailchimp. Basic templates, custom domains (paid), and form integration. Replaces simple Carrd or Leadpages use cases for email-focused landing pages.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Free landing pages without a separate tool. Auto-subscribe visitors to your Mailchimp audience.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Content Optimizer (Standard — $20/mo)</h2><p className="text-muted leading-relaxed mb-2">AI-powered analysis of your email content: subject line suggestions, send time optimization, and engagement predictions. Available on Standard tier.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Data-driven email optimization without a separate A/B testing tool.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Customer Journey Builder (Standard — $20/mo)</h2><p className="text-muted leading-relaxed mb-2">Visual automation builder with branching logic, delays, and conditional paths. More powerful than basic automations. Many users pay for ActiveCampaign ($15/mo) without trying Mailchimp journeys.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Visual automation comparable to ActiveCampaign, included in Standard.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Postcards (Essentials — $13/mo)</h2><p className="text-muted leading-relaxed mb-2">Physical postcard campaigns to your contact list. Unique channel that no other email platform offers. Design in Mailchimp, mail through USPS.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Physical mail marketing integrated with your email data.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Social Posting (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Schedule and publish to Facebook, Instagram, and Twitter directly from Mailchimp. Basic social management without Buffer ($6/channel) or Hootsuite ($149/mo).</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Basic social scheduling without a separate tool.</p></div></section>
      <RelatedLinks tools={["mailchimp"]} comparisons={[]} guides={["is-mailchimp-still-good", "mailchimp-hidden-costs"]} />
    </div></article></>);
}
