import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "5 Asana Features Most People Miss", description: "Asana Starter ($13.49/seat) includes workflow builder and forms. Advanced ($30.49/seat) adds portfolios, goals, and approvals. Underused features that boost team productivity." };
export default function Page() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">5 Asana Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">5 Asana Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">Asana clean interface hides powerful features. Workflow builder, forms, portfolios, and approvals are available but rarely configured by most teams.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Workflow Builder (Starter — $13.49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Build custom rules: when a task moves to Review, assign to manager. When priority is set to High, add to a specific project. Starter tier includes workflow automation.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Native automation without Zapier for internal task management.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Forms (Starter — $13.49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Create intake forms that generate tasks in specific projects with pre-set fields. Perfect for bug reports, content requests, or design briefs. Eliminates form-to-PM-tool integrations.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Structured intake without Typeform + Zapier integration.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Portfolios (Advanced — $30.49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Track multiple projects in one view with status, progress, and ownership. See which projects are on track, at risk, or off track. Replaces spreadsheet-based project trackers.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Executive-level project visibility without a separate reporting tool.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Goals and Milestones (Advanced — $30.49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Set company goals linked to projects and tasks. Track progress automatically. Connect daily work to strategic objectives without a separate OKR tool.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> OKR tracking built into your PM tool.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Approvals (Advanced — $30.49/seat/mo)</h2><p className="text-muted leading-relaxed mb-2">Add approval steps to tasks. Reviewers can approve, request changes, or reject. Creates a structured review process for creative work, content, and designs.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Structured review process without email chains.</p></div></section>
      <RelatedLinks tools={["asana"]} comparisons={[]} guides={["asana-pricing-explained", "is-clickup-better-than-asana", "who-should-not-use-asana"]} />
    </div></article></>);
}
