import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "5 Make Features Most People Miss", description: "Make Core ($10.59/mo) includes data stores, error handling routes, and custom functions. Hidden power features that justify switching from Zapier." };
export default function Page() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">5 Make Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">5 Make Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">Make visual scenario builder gets the attention, but data stores, error routes, custom functions, HTTP modules, and templates marketplace are what make it a power user tool.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Data Stores — Persistent Storage (Core — $10.59/mo)</h2><p className="text-muted leading-relaxed mb-2">Built-in key-value database for storing data between scenario runs. Track processed records, maintain lookup tables, or build simple inventories without a separate database.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Persistent data between automations without Airtable or Google Sheets.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Error Handling Routes (Core — $10.59/mo)</h2><p className="text-muted leading-relaxed mb-2">Add dedicated error routes to any module. When a step fails, route to a fallback action instead of failing the entire scenario. Zapier has no equivalent feature.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Reliable automations that handle failures gracefully instead of breaking silently.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Custom Functions (Pro — $18.82/mo)</h2><p className="text-muted leading-relaxed mb-2">Write custom JavaScript functions within scenarios. Transform data, parse complex formats, or calculate values mid-workflow. Available on Pro tier.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Custom code without n8n complexity. Best of both worlds.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. HTTP/Webhook Modules (Core — $10.59/mo)</h2><p className="text-muted leading-relaxed mb-2">Make any API call to any service, even without a dedicated module. HTTP modules let you connect to tools that do not have official Make integrations.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Connect to any API, not just the 1,800+ built-in integrations.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Templates Marketplace (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Pre-built scenario templates for common workflows. Import and customize instead of building from scratch. Available on all tiers including free.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Faster setup for common automations. Skip the learning curve for standard workflows.</p></div></section>
      <RelatedLinks tools={["make"]} comparisons={[]} guides={["make-pricing-explained", "is-make-better-than-zapier", "migrate-zapier-to-make"]} />
    </div></article></>);
}
