import { Suspense } from "react";
import Link from "next/link";
import ReportClient from "./report-client";

function ReportStatic() {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <section className="border-b border-border bg-surface">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16 text-center">
          <p className="text-xs font-semibold text-accent uppercase tracking-wider mb-3">
            Generated by Sasanova
          </p>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight mb-4">
            SaaS Stack Audit Report
          </h1>
          <p className="text-base text-muted max-w-xl mx-auto">
            An independent analysis of SaaS spending with actionable
            recommendations to reduce costs.
          </p>
        </div>
      </section>

      {/* Example metrics */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-16 space-y-12">
        <section>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Monthly Spend
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-foreground">
                $847
              </p>
              <p className="text-xs text-muted">$10,164/yr</p>
            </div>

            <div className="border border-success/30 rounded-xl p-5 bg-success/5 text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Potential Savings
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-success">
                $312<span className="text-base font-medium">/mo</span>
              </p>
              <p className="text-xs text-success/80">$3,744/yr</p>
            </div>

            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Audit Score
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-yellow-400">
                62%
              </p>
              <p className="text-xs text-muted">Stack efficiency</p>
            </div>

            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Tools Audited
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-accent">
                5
              </p>
              <p className="text-xs text-muted">3 optimal</p>
            </div>
          </div>
          <p className="text-xs text-muted text-center mt-4">
            Example metrics &mdash; your personalized results are loading&hellip;
          </p>
        </section>

        {/* CTA */}
        <section className="text-center">
          <div className="border border-accent/30 rounded-xl p-8 bg-accent/5">
            <h2 className="text-2xl font-extrabold text-foreground mb-3">
              Run Your Own Audit
            </h2>
            <p className="text-sm text-muted mb-6 max-w-md mx-auto">
              Input your current SaaS stack and get a personalized report with
              savings recommendations in under 2 minutes.
            </p>
            <Link
              href="/audit"
              className="inline-flex px-8 py-3.5 text-base font-bold bg-accent text-white rounded-xl hover:brightness-110 transition-all"
            >
              Audit Your Stack Free
            </Link>
          </div>
        </section>
      </div>
    </div>
  );
}

export default function AuditReportPage() {
  return (
    <Suspense fallback={<ReportStatic />}>
      <ReportClient />
    </Suspense>
  );
}
