"use client";

import { useMemo, Suspense } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { tools as allTools, type Tool } from "@/data/tools";
import { ConfidenceBadge, getConfidenceLevel } from "@/components/ConfidenceBadge";

/* ── Types ── */

interface ReportToolData {
  slug: string;
  plan: string;
  teamSize: number;
  cost: number;
  altSlug: string | null;
  altPlan: string | null;
  altCost: number | null;
  savings: number;
}

interface ReportData {
  tools: ReportToolData[];
  totalSpend: number;
  totalSavings: number;
  auditScore: number;
}

/* ── Helpers ── */

function fmt(n: number): string {
  return "$" + n.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

function getToolBySlug(slug: string): Tool | undefined {
  return allTools.find((t) => t.slug === slug);
}

/* ── Component ── */

function AuditReportInner() {
  const searchParams = useSearchParams();

  const reportData = useMemo<ReportData | null>(() => {
    const dataParam = searchParams.get("data");
    if (!dataParam) return null;
    try {
      const decoded = atob(decodeURIComponent(dataParam));
      const parsed = JSON.parse(decoded) as ReportData;
      if (!parsed.tools || !Array.isArray(parsed.tools)) return null;
      return parsed;
    } catch {
      return null;
    }
  }, [searchParams]);

  if (!reportData) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center max-w-md mx-auto px-4">
          <h1 className="text-2xl font-extrabold text-foreground mb-4">Invalid Report Link</h1>
          <p className="text-sm text-muted mb-6">
            This audit report link is invalid or has expired. Run your own audit to generate a new one.
          </p>
          <Link
            href="/audit"
            className="px-6 py-3 text-sm font-semibold bg-accent text-white rounded-lg hover:brightness-110 transition-all"
          >
            Run Your Own Audit
          </Link>
        </div>
      </div>
    );
  }

  const { tools: toolData, totalSpend, totalSavings, auditScore } = reportData;
  const totalAnnualSavings = totalSavings * 12;

  return (
    <div className="min-h-screen">
      {/* ── Header ── */}
      <section className="border-b border-border bg-surface">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16 text-center">
          <p className="text-xs font-semibold text-accent uppercase tracking-wider mb-3">
            Generated by Sasanova
          </p>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight mb-4">
            SaaS Stack Audit Report
          </h1>
          <p className="text-base text-muted max-w-xl mx-auto">
            An independent analysis of SaaS spending with actionable recommendations to reduce costs.
          </p>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-16 space-y-12">
        {/* ── Summary Cards ── */}
        <section>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Monthly Spend
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-foreground">
                {fmt(totalSpend)}
              </p>
              <p className="text-xs text-muted">{fmt(totalSpend * 12)}/yr</p>
            </div>

            <div className="border border-success/30 rounded-xl p-5 bg-success/5 text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Potential Savings
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-success">
                {fmt(totalSavings)}
                <span className="text-base font-medium">/mo</span>
              </p>
              <p className="text-xs text-success/80">{fmt(totalAnnualSavings)}/yr</p>
            </div>

            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Audit Score
              </p>
              <p
                className={`text-2xl lg:text-3xl font-extrabold ${
                  auditScore >= 80
                    ? "text-success"
                    : auditScore >= 50
                      ? "text-yellow-400"
                      : "text-red-400"
                }`}
              >
                {auditScore}%
              </p>
              <p className="text-xs text-muted">Stack efficiency</p>
            </div>

            <div className="border border-border rounded-xl p-5 bg-background text-center">
              <p className="text-xs font-semibold text-muted uppercase tracking-wider mb-1">
                Tools Audited
              </p>
              <p className="text-2xl lg:text-3xl font-extrabold text-accent">
                {toolData.length}
              </p>
              <p className="text-xs text-muted">
                {toolData.filter((t) => t.savings === 0).length} optimal
              </p>
            </div>
          </div>
        </section>

        {/* ── Per-Tool Breakdown ── */}
        <section>
          <h2 className="text-xl font-bold text-foreground mb-6">Per-Tool Breakdown</h2>
          <div className="space-y-4">
            {toolData.map((item, idx) => {
              const tool = getToolBySlug(item.slug);
              const altTool = item.altSlug ? getToolBySlug(item.altSlug) : null;
              const hasAlt = item.altSlug && item.altPlan && item.savings > 0;

              return (
                <div
                  key={`${item.slug}-${idx}`}
                  className="border border-border rounded-xl p-5 bg-background"
                >
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 mb-4">
                    <div>
                      <div className="flex items-center gap-2 flex-wrap mb-1">
                        <h3 className="text-lg font-bold text-foreground">
                          {tool?.name ?? item.slug}
                        </h3>
                        {hasAlt ? (
                          <span className="inline-flex items-center px-2 py-0.5 text-[11px] font-semibold rounded-full border text-yellow-400 bg-yellow-400/10 border-yellow-400/30">
                            Cheaper Exists
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-2 py-0.5 text-[11px] font-semibold rounded-full border text-success bg-success/10 border-success/30">
                            Optimal
                          </span>
                        )}
                        {tool && <ConfidenceBadge level={getConfidenceLevel(tool)} />}
                      </div>
                      <p className="text-sm text-muted">
                        {item.plan} plan &middot; {item.teamSize}{" "}
                        {item.teamSize === 1 ? "seat" : "seats"}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-2xl font-extrabold text-foreground">
                        {fmt(item.cost)}/mo
                      </p>
                      <p className="text-xs text-muted">{fmt(item.cost * 12)}/yr</p>
                    </div>
                  </div>

                  {hasAlt && (
                    <div className="bg-surface border border-border rounded-lg p-4 space-y-2">
                      <div className="flex items-center gap-2">
                        <span className="w-2.5 h-2.5 rounded-full bg-red-400 shrink-0" />
                        <p className="text-sm font-bold text-foreground">
                          {tool?.name ?? item.slug} {item.plan} ({fmt(item.cost)}/mo)
                        </p>
                      </div>
                      <div className="pl-5 space-y-2">
                        <p className="text-sm text-muted">
                          <span className="text-foreground font-medium">Replace with:</span>{" "}
                          {altTool?.name ?? item.altSlug} {item.altPlan} ({fmt(item.altCost ?? 0)}/mo)
                        </p>
                        <p className="text-sm">
                          <span className="text-success font-semibold">
                            Save {fmt(item.savings)}/mo ({fmt(item.savings * 12)}/yr)
                          </span>
                        </p>
                        {altTool && (
                          <div className="flex items-center gap-2 pt-1">
                            <ConfidenceBadge level={getConfidenceLevel(altTool)} />
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {!hasAlt && (
                    <div className="bg-success/5 border border-success/20 rounded-lg p-4">
                      <p className="text-sm text-success font-medium">
                        This is the most cost-effective option in its category at your scale.
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* ── CTA ── */}
        <section className="text-center">
          <div className="border border-accent/30 rounded-xl p-8 bg-accent/5">
            <h2 className="text-2xl font-extrabold text-foreground mb-3">
              Run Your Own Audit
            </h2>
            <p className="text-sm text-muted mb-6 max-w-md mx-auto">
              Input your current SaaS stack and get a personalized report with savings recommendations in under 2 minutes.
            </p>
            <Link
              href="/audit"
              className="inline-flex px-8 py-3.5 text-base font-bold bg-accent text-white rounded-xl hover:brightness-110 transition-all"
            >
              Audit Your Stack Free
            </Link>
          </div>
        </section>

        {/* ── Footer ── */}
        <footer className="text-center border-t border-border pt-8">
          <p className="text-xs text-muted">
            Powered by{" "}
            <Link href="/" className="text-accent hover:underline font-medium">
              Sasanova
            </Link>{" "}
            &mdash; SaaS pricing intelligence
          </p>
          <p className="text-xs text-muted/60 mt-1">
            Data independently verified. Recommendations are automated and based on pricing data, not endorsements.
          </p>
        </footer>
      </div>
    </div>
  );
}

export default function AuditReportPage() {
  return (
    <Suspense fallback={
      <div className="max-w-4xl mx-auto px-4 py-12 text-center">
        <h1 className="text-3xl font-extrabold mb-4">SaaS Stack Audit Report</h1>
        <p className="text-muted">Loading your audit report...</p>
      </div>
    }>
      <AuditReportInner />
    </Suspense>
  );
}
