import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "6 Slack Features Most People Miss", description: "Slack Pro ($8.75/user/mo) includes Workflow Builder, Huddles, Canvas, and Clips. Free includes unlimited messages (90-day limit). Productivity features beyond basic chat." };
export default function Page() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">6 Slack Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">6 Slack Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">Slack is a messaging tool on the surface. But Workflow Builder, Canvas (docs), Huddles (quick calls), Clips (video messages), and channel organization features turn it into a productivity platform.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Workflow Builder (Pro — $8.75/user/mo)</h2><p className="text-muted leading-relaxed mb-2">Build no-code automations within Slack: approval workflows, standup bots, onboarding checklists, and custom forms. Replaces simple Zapier automations for Slack-centric workflows.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Internal automation without Zapier for Slack-native workflows.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. Canvas — Built-in Docs (Pro — $8.75/user/mo)</h2><p className="text-muted leading-relaxed mb-2">Create rich documents within Slack channels. Meeting notes, project briefs, and reference docs live alongside conversations. Competes with Notion for lightweight team docs.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Team docs where conversations happen. No switching to Notion for quick references.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Huddles — Instant Voice/Video (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">One-click audio/video calls within any channel or DM. Screen sharing included. Free tier supports 1:1 calls. Pro supports up to 50 people. Faster than scheduling a Zoom call.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Instant calls without calendar scheduling. Replaces casual Zoom meetings.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Clips — Async Video Messages (Pro — $8.75/user/mo)</h2><p className="text-muted leading-relaxed mb-2">Record and share short video or audio clips in any channel. Viewers can react and reply with their own clips. Competes with Loom ($12.50/user/mo) for async video.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Async video updates without a Loom subscription.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Connect — External Collaboration (Pro — $8.75/user/mo)</h2><p className="text-muted leading-relaxed mb-2">Share Slack channels with external organizations. Both companies use their own Slack workspace but share a connected channel. Replaces email chains with clients and partners.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Real-time client communication without giving them access to your full workspace.</p></div></section>
      <RelatedLinks tools={["slack"]} comparisons={[]} guides={["6. Scheduled Messages (Free — $0)|Write messages now", " schedule them for later. Perfect for async teams across time zones. Available on all tiers including free. Most users type and send immediately.|Timezone-respectful communication. Write at midnight", " deliver at 9 AM.|slack-pricing-explained", "who-should-not-use-slack", "discord-vs-slack-for-communities"]} />
    </div></article></>);
}
