import type { Metadata } from "next";
import Link from "next/link";
import RelatedLinks from "@/components/RelatedLinks";
export const metadata: Metadata = { title: "6 ClickUp Features Most People Miss", description: "ClickUp Free includes Docs, Whiteboards, and unlimited members. Unlimited ($10/seat) adds Gantt, time tracking, and dashboards. Hidden power features most teams overlook." };
export default function ClickupFeaturesMostPeopleMissPage() {
  return (<><div className="border-b border-border bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-3"><nav className="flex items-center gap-1.5 text-xs text-muted"><Link href="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link href="/guides" className="hover:text-accent transition-colors">Guides</Link><span>/</span><span className="text-foreground font-medium truncate">ClickUp Features Most People Miss</span></nav></div></div>
    <div className="border-b border-border"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><span className="inline-block text-[10px] font-semibold uppercase tracking-wider text-accent bg-accent-light px-2.5 py-1 rounded-full mb-4">Hidden Features</span><h1 className="text-3xl lg:text-4xl font-extrabold tracking-tight mb-4">6 ClickUp Features Most People Miss</h1><p className="text-muted text-lg leading-relaxed">ClickUp packs more features than any other PM tool. Most teams use tasks and boards. Here are 6 features that justify the tool but most people never configure.</p><div className="flex items-center gap-3 mt-4 text-xs text-muted"><span>10 min read</span><span className="w-1 h-1 rounded-full bg-border" /><span>Updated March 2026</span></div></div></div>
    <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="prose-custom space-y-8">
      <section><h2 className="text-xl font-bold mb-3">1. Clips — Screen Recording (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Record your screen directly in ClickUp and attach clips to tasks. Replaces Loom for internal communication. Available on all tiers including Free Forever.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Async video updates without a Loom subscription ($12.50/user/mo). Clips live alongside tasks for context.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">2. ClickUp Docs with Nested Pages (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Full document editor with nested pages, real-time collaboration, and task embedding. Most teams use Notion or Google Docs alongside ClickUp without realizing Docs are built in.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Docs and tasks in one tool. Eliminates context switching between Notion ($12/user/mo) and your PM tool.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">3. Whiteboards (Free — $0)</h2><p className="text-muted leading-relaxed mb-2">Collaborative whiteboarding with the ability to convert sticky notes directly into ClickUp tasks. Available on Free tier. Competes with Miro ($8/user/mo) and FigJam.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Brainstorming to task creation in one flow. No separate Miro subscription needed.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">4. Time Tracking (Unlimited — $10/member/mo)</h2><p className="text-muted leading-relaxed mb-2">Built-in time tracking on any task. Start and stop timers, add manual entries, and view time reports by project, person, or date range. Replaces Toggl ($9/user/mo) or Harvest ($12/user/mo).</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Time tracking alongside tasks without a separate tool. Saves $9-$12/user/month.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">5. Goals and OKRs (Unlimited — $10/member/mo)</h2><p className="text-muted leading-relaxed mb-2">Set goals with measurable targets linked to tasks, lists, or custom metrics. Track progress automatically as tasks complete. Replaces dedicated OKR tools like Lattice or 15Five for basic goal tracking.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Goals connected to daily work without a separate OKR platform.</p></div></section>
      <section><h2 className="text-xl font-bold mb-3">6. Custom Automations (Unlimited — $10/member/mo)</h2><p className="text-muted leading-relaxed mb-2">Build if-then automations triggered by task status changes, assignee changes, due dates, or custom fields. Unlimited tier includes 1,000 automations per month. Business ($19/member/mo) gets 10,000.</p><div className="bg-surface rounded-lg border border-border p-3"><p className="text-sm text-muted"><strong className="text-foreground">Why This Matters:</strong> Workflow automation without Zapier ($29.99/mo) for internal task management.</p></div></section>
      <RelatedLinks tools={["clickup"]} comparisons={["asana-vs-clickup"]} guides={["clickup-pricing-explained", "is-clickup-better-than-asana", "who-should-not-use-clickup"]} />
    </div></article></>);
}
